jobs:
  - name: dataworks-github-config-pr
    plan:
      - get: dataworks-github-config-pr
        trigger: true
        version: every
      - put: dataworks-github-config-pr
        params:
          path: dataworks-github-config-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-github-config: dataworks-github-config-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-github-config: dataworks-github-config-pr
        on_failure:
          put: dataworks-github-config-pr
          params:
            path: dataworks-github-config-pr
            status: failure
        on_success:
          put: dataworks-github-config-pr
          params:
            path: dataworks-github-config-pr
            status: success
